### ISSUE TITLE
Extension stops working

### ISSUE THREAD

**Issue by brokoler** [Cizzuk/CSE#2]
Hello,

I discovered your app and love it!
It's much better than other alternatives in my point of view, since it does require only minimal permissions and it's open source.

Sadly the extension is only working a few minutes for me.
I enabled all permissions (Enabled extension and gave full permission to all search sites).
The extension works then, but just for a few minutes. Afterwards it is using the default search engine of Safari every time (DuckDuckGo in my case).

When I disable and enable the extension is Safari settings again, it is working but just until the issue reappears.
Would be glad if this can be fixed, I'm using the latest version 2.2 with iOS 17.5.1 on an iPhone 12.

I will recommend your extension to anyone when this is fixed, thanks for your work!

**Comment by Cizzuk** [comment]
Thank you.
I have confirmed this bug and will work on fixing it in the next version.

However, I will be busy during this week, so the fix is scheduled for next week or later.

**Comment by Cizzuk** [comment]
The bug has been fixed in v2.3.
Once the App Store review is complete, the update will be available.
@brokoler thanks for the bug report!
