### ISSUE TITLE
[Enhancement Request] Add Support For All Default iOS Default Browsers 

### ISSUE THREAD

**Issue by DavidSchechter** [Cizzuk/CSE#3]
Hi,
This is a great extension which is helping to customize Safari’s search engine.

Issue:
CSE lists DuckDuckGo, Sogou and Yandex

CSE does **not** list Google, Yahoo, Bing or Ecosia.

Request:
It would be greatly appreciated if an enchantment can be made to include all these (or more) in the available list.

I would be more than happy to contribute such an enchantment to this repo via PR, if that would be helpful.

Thanks and feedback will be appreciated

**Comment by DavidSchechter** [comment]
Suggestion:

In file content.js the following logic could be added:

if (Domain.includes('google')) {
  // The current URL is in any *.google.* domain
}

**Comment by Cizzuk** [comment]
This is not possible.
The domain must be specified in manifest.json first.
https://github.com/Cizzuk/CSE/blob/571526b75363e1096df5c1960670285cf5fcbb1d/Custom%20Search%20Engine%20Extension/Resources/manifest.json#L24
I could set this to all domains (`"matches": [ "<all_urls>" ]`) but CSE should work with minimal permissions.

**Comment by DavidSchechter** [comment]
Thanks for sharing that information.
I wasn’t aware that the manifest.js was used for the permission enabling.

It’s does seem that ccTLDs is supported.
(Per documentation I found from Mozilla and chrome https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns#special https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns)

It does seem the only available options are:
1. List <all_urls> - not ideal 
2. Limit support to specific TLD of google / yahoo / bing / ecosia - not ideal either 
3. Specify every single localized TLD of google / yahoo / bing / ecosia - would require a user to enable each one manually and finds all existing TLDs of these domains 

I could be missing something

**Comment by Cizzuk** [comment]
https://github.com/Cizzuk/CSE/commit/b48d3061ce32a372b950c8108642c53595fc1a4b
I have tested with the regional settings for the United States, Japan, Mainland China, Taiwan, Hong Kong, and Russia.
I have added Google, Yahoo, Bing, Ecosia, Baidu, and 360 Search as options.
This should cover everything needed.

**Comment by DavidSchechter** [comment]
Thanks again for making these great enhancements.

Small follow up question:

When do you think this change would be released and made available in the App Store?

**Comment by Cizzuk** [comment]
We will have to wait for Apple's review.
It should take a few days at most.
