### ISSUE TITLE
[BUG] Tapping any tab in Google search redirects back to Web tab when top URL includes Google search engine

### ISSUE THREAD

**Issue by DavidSchechter** [Cizzuk/CSE#9]
Root cause:
Top of url included support url. Redirect / reset of url is done always without checking for additional or modifier

Sets to reproduce:

- Set top of url to - https://google.com/search?udm=14&q= (this is a redirect to the new “web” tab in google search).
- Set default search engine as - Google - both in CSE and Safari Settings
- Attempt to make a search
- Try changing to images tab or shopping tab or back to all tab
- You get redirected back to web tab

Issue isn’t reproducible if DuckDuckGo is set as the default search engine both in CSE and Safari Settings.

Thank you in advance

**Comment by Cizzuk** [comment]
This is a known bug, but I have not found a way to fix it so far.  
This bug occurs in Google, 360Search, and Yandex.
